### PR TITLE
Remove unused parameter from method definition

### PR DESCRIPTION
**Pull request by NestorTejero**
This produced the error `TypeError: _tuple_literal() missing 1 required positional argument: 'd'` on line 316. Introduced in commit https://github.com/PyMySQL/mysqlclient-python/commit/ca4317a6b5ffc4c78c711123b52dfda400d00eb5, release [1.3.11](https://github.com/PyMySQL/mysqlclient-python/releases/tag/1.3.11).

### CODE REVIEW

**Comment by methane** [comment]
Could you add test for it?
I never use the feature.  So I will break it again and again if there is no test.

**Comment by NestorTejero** [comment]
@methane  I got this error while using SQLAlchemy, which in its turn was using `cursor()`. I will try to isolate it so we can have a test!
